apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: backend
  name: backend-service
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081 # Optional: Specify a fixed NodePort (must be in the range 30000-32767)
  type: NodePort
  selector:
    io.kompose.service: backend
