apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - args:
            - sh
            - -c
            - sqlx migrate run && ./typings_actix_postgres
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@db:5432/typings_users
          image: kurgiorgis/backend:1.0
          name: backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /app/migrations
              name: backend-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: backend-cm0
          name: backend-cm0
